### ISSUE TITLE
Incorporate SimpleDB?

### ISSUE THREAD

**Issue by jeffposnick** [wibblymat/shed#18]
@inexorabletash has written a clean, Promise-based wrapper around IndexedDB at https://gist.github.com/inexorabletash/c8069c042b734519680c He has no plans on releasing it himself, but he's happy enough if it gets public usage (and would like feedback from developers).

@wibblymat, what are your thoughts on rolling this into your library and exposing the interface via `shed.simpleDB`? This does amount to some degree of feature-creep, but at the same time, if `shed`'s goal is to simplify common service worker usage patterns, then providing a friendly way to interact with IndexedDB can help achieve that.

**Comment by wibblymat** [comment]
I'm tending towards not including this right now.

Not everyone will need a storage solution, and for those that do there are other wrappers (like PouchDB or localForage) that would be equally as valid. People will choose the one they are familiar with.

If we find that we need to include a solution for internal use then that's a different matter. Exposing that would be fine.
