### ISSUE TITLE
Add stale-while-revalidate option

### ISSUE THREAD

**Issue by jeffposnick** [wibblymat/shed#3]
Stale-while-revalidate, as described at http://jakearchibald.com/2014/offline-cookbook/, is a useful pattern to implement.

**Comment by wibblymat** [comment]
`fastest` has *almost* the same behavior. It will fetch from the network and update the cache every time, even if the returned result comes straight from the cache. The only time the behavior would be different is if the request was previously cached, but somehow the cache fetch took longer than the network fetch.

**Comment by jeffposnick** [comment]
Makes sense. `fastest` it is.
